import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import React, { useRef, useState } from "react";
import BlogItem from "../../components/BlogItem";
import PageTitle from "../../components/PageTitle";
import { useRouter } from "next/router";
import { BlogItemType, ProductItemType } from "../../types/type";
interface Props {
  data: BlogItemType[];
}

const Blog: NextPage<Props> = ({ data }) => {
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);
  const router = useRouter();
  const inputValue = useRef<HTMLInputElement>(null);

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    const value = inputValue?.current?.value;

    router.push({
      pathname: "/blogs",
      query: {
        category_like: value,
      },
    });
    if (inputValue.current) {
      inputValue.current.value = "";
    }
  };
  const handleCategoryClick = (category: string) => {
    setSelectedCategory(category);

    router.push({
      pathname: "/blogs",
      query: {
        category_like: category,
      },
    });
  };
  return (
    <>
      <Head>
        <title>Store - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title="Blog" />

      <section className="bg0 p-t-62 p-b-60">
        <div className="container">
          <div className="row">
            <div className="col-md-8 col-lg-9 p-b-80">
              <div className="p-r-45 p-r-0-lg">
                {data.length === 0 ? (
                  <p>There are no results with your search.</p>
                ) : (
                  data.map((item) => <BlogItem data={item} key={item.id} />)
                )}
              </div>
            </div>

            <div className="col-md-4 col-lg-3 p-b-80">
              <div className="side-menu">
                <form
                  className="bor17 of-hidden pos-relative"
                  onSubmit={handleSubmit}
                >
                  <input
                    className="stext-103 cl2 plh4 size-116 p-l-28 p-r-55"
                    type="text"
                    name="search"
                    placeholder="Search"
                    ref={inputValue}
                  />

                  <button className="flex-c-m size-122 ab-t-r fs-18 cl4 hov-cl1 trans-04">
                    <i className="zmdi zmdi-search"></i>
                  </button>
                </form>

                <div className="p-t-55">
                  <h4 className="mtext-112 cl2 p-b-33">Categories</h4>

                  <ul>
                    <li className="bor18">
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => handleCategoryClick("fashion")}
                      >
                        Fashion
                      </button>
                    </li>

                    <li className="bor18">
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => handleCategoryClick("Beauty")}
                      >
                        Beauty
                      </button>
                    </li>

                    <li className="bor18">
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => handleCategoryClick("streetstyle")}
                      >
                        Street Style
                      </button>
                    </li>

                    <li className="bor18">
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => handleCategoryClick("lifestyle")}
                      >
                        Life Style
                      </button>
                    </li>

                    <li className="bor18">
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => handleCategoryClick("diy")}
                      >
                        DIY & Crafts
                      </button>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default Blog;

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const streetstyle = query.category_like;

  let link: string;

  if (streetstyle) {
    link = `http://localhost:5001/blogs?category_like=${streetstyle}`;
  } else {
    link = "http://localhost:5001/blogs";
  }
  const res = await fetch(link);
  const data: BlogItemType = await res.json();

  return {
    props: { data },
  };
};
