import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import CategoryPicker from "../components/CategoryPicker";
import FeaturedBlogs from "../components/FeaturedBlogs";
import FeaturedProducts from "../components/FeaturedProducts";
import { BannerType, BlogItemType, ProductItemType } from "../types/type";

interface Props {
  dataBanner: BannerType;
  dataFeauterdProducts: ProductItemType[];
  dataFeaturedBlogs: BlogItemType[];
}

const Home: NextPage<Props> = ({
  dataBanner,
  dataFeauterdProducts,
  dataFeaturedBlogs,
}) => {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner preTitle={dataBanner.preTitle} title={dataBanner.title} />

      <CategoryPicker />

      <FeaturedProducts dataFeauterdProducts={dataFeauterdProducts} />

      <FeaturedBlogs dataFeaturedBlogs={dataFeaturedBlogs} />
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const [resBanner, resFeauterdProducts, resFeaturedBlogs] = await Promise.all([
    fetch("http://localhost:5001/banner_content"),
    fetch("http://localhost:5001/products/?_limit=4"),
    fetch("http://localhost:5001/blogs/?_limit=3"),
  ]);

  const [dataBanner, dataFeauterdProducts, dataFeaturedBlogs] =
    await Promise.all([
      resBanner.json(),
      resFeauterdProducts.json(),
      resFeaturedBlogs.json(),
    ]);

  return {
    props: { dataBanner, dataFeauterdProducts, dataFeaturedBlogs },
  };
};
