import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import BlogItem from "../components/BlogItem";
import PageTitle from "../components/PageTitle";
import ProductItem from "../components/ProductItem";
import { BlogItemType, ProductItemType } from "../types/type";
interface Props {
  blogs: BlogItemType[];
  products: ProductItemType[];
}
const Search: NextPage<Props> = ({ blogs, products }) => {
  return (
    <>
      <Head>
        <title>Store - Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title="Search" />

      <div className="bg0 m-t-23 p-b-140 mt-5">
        <div className="container">
          <>
            <h2 className="mb-5">Blogs</h2>
            <div className="row isotope-grid">
              {blogs.map((item) => (
                <div className="col-4">
                  <BlogItem data={item} />
                </div>
              ))}
            </div>
          </>

          <>
            <h2 className="mb-5">Products</h2>
            <div className="row isotope-grid">
              {products.map((item) => (
                <ProductItem
                  img={item.img}
                  price={item.price}
                  title={item.title}
                  key={item.id}
                  id={item.id}
                />
              ))}
            </div>
          </>
        </div>
      </div>
    </>
  );
};

export default Search;

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const searchQuery = query.q as string;

  try {
    const [blogsRes, productsRes] = await Promise.all([
      fetch(`http://localhost:5001/blogs?q=${searchQuery}`),
      fetch(`http://localhost:5001/products?q=${searchQuery}`),
    ]);

    const [blogs, products] = await Promise.all([
      blogsRes.json(),
      productsRes.json(),
    ]);

    return {
      props: {
        products,
        blogs,
      },
    };
  } catch (err) {
    return {
      notFound: true,
    };
  }
};
